### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoicing#109]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] account_group_invoice_lines
- [x] account_invoice_check_total - By @ThomasBinsfeld - #162 
- [ ] account_invoice_customer_ref_unique
- [ ] account_invoice_force_number
- [ ] account_invoice_line_description
- [ ] account_invoice_line_sort
- [x] account_invoice_merge - By @BT-hstoeckle - #209 
- [x] account_invoice_merge_payment - By @cubells - #232 
- [x] account_invoice_merge_purchase - By @cubells - #233 
- [ ] account_invoice_partner
- [ ] account_invoice_period_usability
- [x] account_invoice_pricelist - By @sergio-teruel - #211 
- [ ] account_invoice_rounding
- [ ] account_invoice_shipping_address - By @fshahy https://github.com/OCA/account-invoicing/pull/135
- [ ] account_invoice_template
- [ ] account_invoice_uom
- [ ] account_invoice_validation_workflow
- [x] account_invoice_supplier_ref_unique - By @ThomasBinsfeld - #161
- [ ] account_invoice_zero_autopay
- [x] account_payment_term_extension by @jcoux - #141
- [x] invoice_fiscal_position_update > account_invoice_fiscal_position_update - By @sergio-teruel - #223 
- [ ] product_customer_code_invoice
- [X] ~~sale_order_partial_invoice~~ Not needed anymore as possible in core
- [ ] stock_invoice_picking_incoterm
- [ ] stock_picking_invoicing - By @flotho merged in one module in #140
- [ ] stock_picking_invoicing_unified - By @flotho merged in one module in #140

**Comment by ghost** [comment]
@pedrobaeza I will start by migrating account_invoice_shipping_address :)

**Comment by pedrobaeza** [comment]
Cool, I have written it in the summary

**Comment by flotho** [comment]
Hi, 

I'm about to rewrite the stock_pricking_invoice part. As there is no more invoicing defined neither on picking nor on moves everything has to be rewrite

**Comment by pedrobaeza** [comment]
Good idea. You can incorporate https://github.com/OCA/account-invoicing/tree/8.0/stock_picking_invoicing_unified logic to this module.

**Comment by flotho** [comment]
Hi @pedrobaeza 

Do you confirm my analysis, no more invoicing is available on stocks move, pickings etc...

**Comment by pedrobaeza** [comment]
Yeah, I checked that for the commission modules, and sadly there's no more picking invoicing (or it's very hidden, but I don't think so).

**Comment by flotho** [comment]
so You could reference this : https://github.com/OCA/account-invoicing/pull/140

**Comment by pedrobaeza** [comment]
Thanks! Written in the main section. Another feature you can take into account is https://github.com/OCA/stock-logistics-workflow/pull/193

**Comment by flotho** [comment]
@pedrobaeza ,

What is the advice for refrencing part of odoo work in this module? Do I need to specify what parts are concerned or is it sufficient to add Odoo SA in the contributors?

**Comment by pedrobaeza** [comment]
You just have to reference it on contributors/header copyright, and put a disclaimer similar like this link on the README: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#backporting-odoo-modules

**Comment by jcoux** [comment]
Hi,
I will work on `account_payment_term_extension` module.

**Comment by pedrobaeza** [comment]
@jcoux, there are now 2 modules in OCA about payment terms. Please see also https://github.com/OCA/account-payment/tree/8.0/account_payment_term_multi_day and see if both can be merged in one or which one is more suitable before making the migration.

**Comment by jcoux** [comment]
@pedrobaeza, thanks for your informations.
@gurneyalex needs of my migration quickly.
So, I have not enough time to merge both modules in one.
I have migrated the `account_payment_term extension` module on the PR https://github.com/OCA/account-invoicing/pull/141

**Comment by flotho** [comment]
Hi,
I think this one could be reviewed: https://github.com/OCA/account-invoicing/pull/152

**Comment by quintanapablo** [comment]
Where can I find a guide, training, lecture, video, etc. on what is required to migrate a module to the 9.0 branch. I want to help but need the very basic guidelines. Thanks!

**Comment by gurneyalex** [comment]
@quintanapablo ask on the contributors mailing list (contributors at odoo-community.org)

**Comment by pangoSE** [comment]
Hi. I understood that the swedish functional consultants vertel are aiming for jumping over a version when upgrading existing customers (e.g. 8.0 -> 10.0). Is this common? Can this explain the relatively meager effort to migrate to 9.0 that we have seen so far?

**Comment by pedrobaeza** [comment]
This issue is only for tracking assignments on the migration tasks, so please don't start philosophical discussions about versions and so on. There are forums and mailing lists for that.

**Comment by pangoSE** [comment]
Ok :)

**Comment by cierek** [comment]
Hi,

Could you sign me up for:
account_invoice_force_number
Will upload module tomorrow.
Thanks,
Piotr
