### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-invoicing#1250]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_global_discount - By @pedrobaeza - #1724
- [x] account_invoice_alternate_payer - By @ChrisOForgeFlow - #1492
- [x] account_invoice_blocking - By @AnizR - #1258
- [x] account_invoice_change_currency - By @ljsalvatierra-factorlibre - #1261
- [x] account_invoice_check_picking_date - By @Shide - #1947
- [x] account_invoice_check_total - By @AnizR - #1253
- [x] account_invoice_crm_tag - By @ernesto-garcia-tecnativa - #1572
- [x] account_invoice_customer_no_autofollow - By @sbidoul - #1781
- [x] account_invoice_date_due - By @smussie - #1447
- [x] account_invoice_default_code_column - By @legalsylvain - #1654
- [x] account_invoice_discount_date - By @Shide - #1886
- [x] account_invoice_discount_display_amount - By @samoros1 - #1623
- [x] account_invoice_fiscal_position_update - By @ljsalvatierra-factorlibre - #1263
- [x] account_invoice_fixed_discount - By @PieterPaulussen - #1488
- [x] account_invoice_force_number - By @heliaktiv - #1441
- [ ] account_invoice_mass_sending - By @BT-anieto - #1529
- [x] account_invoice_merge - By @nguyenminhchien - #1400
- [ ] account_invoice_mode_weekly - By @rousseldenis - #1514
- [x] account_invoice_payment_retention - By @Saran440 - #1597
- [x] account_invoice_payment_term_date_due - By @BT-anieto - #1607
- [ ] account_invoice_pricelist - By @hildickethan-S73 - #1337
- [x] account_invoice_pricelist_sale - By @nguyenminhchien - #1415
- [x] account_invoice_refund_line_selection - By @RodrigoBM - #1466
- [x] account_invoice_refund_link - By @ljsalvatierra-factorlibre - #1264
- [x] account_invoice_refund_reason - By @BT-anieto - #1612
- [ ] account_invoice_search_by_reference - By @dsolanki-initos - #1455
- [x] account_invoice_section_sale_order - By @rven - #1451
- [x] account_invoice_show_currency_rate - By @ACheung-FactorLibre - #1522
- [ ] account_invoice_supplier_ref_unique
- [x] account_invoice_supplier_self_invoice - By @vince-dynapps - #1369
- [x] account_invoice_supplierinfo_update - By @legalsylvain - #1436
- [x] account_invoice_supplierinfo_update_discount - By @legalsylvain - #1444
- [x] account_invoice_supplierinfo_update_qty_multiplier - By @legalsylvain - #1653
- [ ] account_invoice_tax_note
- [x] account_invoice_tax_required - By @ThomasBinsfeld - #1259
- [x] account_invoice_transmit_method - By @alexis-via - #1299
- [x] account_invoice_tree_currency - By @alan196 - #1385
- [ ] account_invoice_triple_discount
- [ ] account_invoice_uom_column - By @legalsylvain - #1655
- [x] account_invoice_validation_queued - By @Saran440 - #1694
- [x] account_invoice_warn_message - By @RogerSans - #1783
- [x] account_mail_autosubscribe - By @Vandan-OSI - #1434
- [x] account_menu_invoice_refund - By @RodrigoBM - #1325
- [ ] account_move_exception
- [ ] account_move_post_block
- [x] account_move_substate - By @bosd - #1568
- [x] account_move_tier_validation - By @hbrunn - #1373
- [ ] account_move_tier_validation_forward
- [x] account_receipt_send - By @anddago78 - #1468
- [x] account_tax_group_widget_base_amount - By @dsolanki-initos - #1482
- [x] acount_invoice_triple_discount - By @ramiadavid - #1269
- [x] partner_invoicing_mode - By @StefanRijnhart - #1295
- [x] partner_invoicing_mode_at_shipping - By @StefanRijnhart - #1295
- [x] partner_invoicing_mode_monthly - By @StefanRijnhart - #1295
- [x] patch - By @anddago78 - #1468
- [x] portal_account_personal_data_only - By @stefan-tecnativa - #1588
- [ ] product_form_account_move_link - By @JaumeBforgeFlow - #1336
- [x] purchase_stock_picking_return_invoicing - By @Yadier-Tecnativa - #1454
- [x] sale_invoicing_date_selection - By @sergiobstoj - #1780
- [x] sale_line_refund_to_invoice_qty - By @JavierIniesta - #1461
- [x] sale_line_refund_to_invoice_qty_skip_anglo_saxon - By @JasminSForgeFlow - #1581
- [x] sale_order_invoicing_grouping_criteria - By @JavierIniesta - #1300
- [x] sale_order_invoicing_qty_percentage - By @carolinafernandez-tecnativa - #1639
- [x] sale_order_invoicing_queued - By @sergiobstoj - #1769
- [x] sale_timesheet_invoice_description - By @dsolanki-initos - #1475
- [x] stock_picking_invoicing - By @mbcosta - #1465
- [x] stock_picking_return_refund_option - By @Yadier-Tecnativa - #1440

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by SoniaViciana** [comment]
* account_invoice_check_total -> https://github.com/OCA/account-invoicing/pull/1253

**Comment by ljsalvatierra-factorlibre** [comment]
Hi @sbidoul 

I have an open PR -> https://github.com/OCA/account-invoicing/pull/1261

Also, I am currently working on migrating `account_invoice_fiscal_position_update`.

**Comment by ljsalvatierra-factorlibre** [comment]
Hi @sbidoul 

I have now two open PRs and currently working on migrating `account_invoice_refund_link`.

https://github.com/OCA/account-invoicing/pull/1261

https://github.com/OCA/account-invoicing/pull/1263

**Comment by ramiadavid** [comment]
Hi @sbidoul 
 I am currently working on migrating `acount_invoice_triple_discount`

**Comment by JavierIniesta** [comment]
Hi @sbidoul !

I am currently working on migrating `sale_order_invoicing_grouping_criteria`

**Comment by mourad-ehm** [comment]
HI @JavierIniesta,
Thanks for migration.
Could you split sale_order_invoicing_grouping_criteria in 2 modules ?
invoicing_grouping_criteria and sale_order_invoicing_grouping_criteria .
invoicing_grouping_criteria  can be used with the module https://github.com/OCA/account-invoicing/tree/14.0/account_invoice_merge

**Comment by mourad-ehm** [comment]
Hi @sbidoul, 
What do you think about my suggestion ?

**Comment by pedrobaeza** [comment]
The module is too simple to be split IMO. If you want compatibility with `account_invoice_merge`, put the needed hooks in the base one, and develop `account_invoice_merge_grouping_criteria` o similar.

**Comment by RodrigoBM** [comment]
Migration account_menu_invoice_refund module from v13 PR #1325

**Comment by ljsalvatierra-factorlibre** [comment]
Hi, how can we speed up the merging process?

**Comment by BT-atornero** [comment]
Hi @sbidoul  !

I am currently working on migrating ```sale_order_invoicing_grouping_criteria```

**Comment by BT-atornero** [comment]
Hi @sbidoul !

I am currently working on migrating ```account_invoice_supplier_ref_unique```

**Comment by alan196** [comment]
I'll start working on account_invoice_tree_currency

**Comment by alan196** [comment]
https://github.com/OCA/account-invoicing/pull/1385 for account_invoice_tree_currency

**Comment by nguyenminhchien** [comment]
**account_invoice_merge**: [#1400](https://github.com/OCA/account-invoicing/pull/1400)

**Comment by nguyenminhchien** [comment]
account_invoice_pricelist_sale: https://github.com/OCA/account-invoicing/pull/1415

**Comment by astirpe** [comment]
There's no need to port `account_move_tier_validation_forward` since the full functionality is already provided by `base_tier_validation_forward`

**Comment by jado95** [comment]
> I am currently working on migrating `account_invoice_supplier_ref_unique`

Hello @BT-atornero . Have you update on migration of account_invoice_supplier_ref_unique?

**Comment by smussie** [comment]
I am working on migrating **account_invoice_date_due** : #1447

**Comment by rven** [comment]
Working on **account_invoice_section_sale_order**: https://github.com/OCA/account-invoicing/pull/1451

**Comment by JavierIniesta** [comment]
Hi!
I am currently working on migrating `sale_line_refund_to_invoice_qty`: #1461

**Comment by RodrigoBM** [comment]
I am currently working on migrating account_invoice_refund_line_selection: https://github.com/OCA/account-invoicing/pull/1466

**Comment by BT-nfrancisco** [comment]
> > I am currently working on migrating `account_invoice_supplier_ref_unique`
> 
> Hello @BT-atornero . Have you update on migration of account_invoice_supplier_ref_unique?

I think he will not work anymore in this module. Here is the [closed PR](https://github.com/OCA/account-invoicing/pull/1350/files#diff-a3624e783c2e5dfe0fb484b37d6b120b803885a7e076539f3c3ad413d3ec3be9) if someone wants to take a look.

**Comment by ttorresllabres** [comment]
I am currently working on migrating account_invoice_date_due

**Comment by pausanchezqubiq** [comment]
Working on migration account_invoice_payment_term_date_due https://github.com/OCA/account-invoicing/pull/1473

**Comment by BT-anieto** [comment]
account_invoice_refund_reason to be added #1494

**Comment by ghost** [comment]
Hi, I am currently working on migrating `account_invoice_show_currency_rate` from v13: https://github.com/OCA/account-invoicing/pull/1522

**Comment by BT-anieto** [comment]
Working on **account_invoice_mass_sending**

**Comment by samoros1** [comment]
Hi @sbidoul
I am currently working on migrating **account_invoice_discount_display_amount**

**Comment by nbadino** [comment]
`account_receipt_base` is missing

**Comment by RogerSans** [comment]
Workin on account_invoice_warn_message https://github.com/OCA/account-invoicing/pull/1783
