### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoicing#317]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_group_invoice_line
- [x] account_invoice_blocking - By @astirpe - #331 
- [x] account_invoice_check_total - By @rven - #363 
- [x] account_invoice_customer_ref_unique - By @astirpe - #347 
- [x] account_invoice_fiscal_position_update - By @RoelAdriaans - #381 
- [x] account_invoice_force_number - By @OpenCode  - #341 
- [ ] account_invoice_kanban
- [x] account_invoice_line_description - By @amcor - #387 
- [ ] account_invoice_line_sequence - By @amcor - #388 
- [ ] account_invoice_line_sort - By @cristinamartinrod - #413
- [ ] account_invoice_merge - ~~By @adrian-pesol - #365~~ By @ValentinVinagre - #422 
- [ ] account_invoice_merge_attachment
- [ ] account_invoice_merge_payment
- [ ] account_invoice_merge_purchase
- [ ] account_invoice_partner
- [ ] account_invoice_period_usability
- [x] account_invoice_pricelist - By @amcor - #390 
- [x] account_invoice_refund_link - By @oihane - #325 
- [ ] account_invoice_refund_option - By @ThomasBinsfeld - #431
- [ ] account_invoice_rounding
- [x] account_invoice_supplier_ref_unique - By @astirpe - #347 
- [ ] account_invoice_supplierinfo_update
- [ ] account_invoice_template
- [ ] account_invoice_transmit_method - ~~By @jarmokortetjarvi - #376~~ By @sergio-teruel - #614 
- [x] account_invoice_triple_discount - By @xavierjimenez - #370 
- [ ] account_invoice_uom
- [ ] account_invoice_validation_workflow
- [x] account_invoice_view_payment - ~~By @AMhadhbi - #399~~ By @mreficent - #403 
- [x] ~~account_invoice_zero_autopay~~ Not needed - In core
- [x] account_payment_term_extension - ~~By @NachoSerra - #328~~ - By @cubells - #375 
- [ ] product_customer_code_invoice
- [x] purchase_batch_invoicing - By @chienandalu - #445 
- [ ] sale_order_partial_invoice
- [x] sale_timesheet_invoice_description - By @astirpe - #334 
- [ ] stock_invoice_picking_incoterm
- [ ] stock_picking_invoicing

**Comment by oihane** [comment]
account_invoice_refund_link https://github.com/OCA/account-invoicing/pull/325

**Comment by astirpe** [comment]
account_invoice_blocking https://github.com/OCA/account-invoicing/pull/331

**Comment by astirpe** [comment]
sale_timesheet_invoice_description https://github.com/OCA/account-invoicing/pull/334

**Comment by OpenCode** [comment]
account_invoice_force_number #341

**Comment by astirpe** [comment]
account_invoice_supplier_ref_unique #347

**Comment by rven** [comment]
[11.0] [MIG] account_invoice_check_total: Migration to 11.0 #363

**Comment by OpenCode** [comment]
@pedrobaeza #341 #347 #325 and #334 are merged

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by jarmokortetjarvi** [comment]
account_invoice_transmit_method #376

**Comment by ghost** [comment]
account_invoice_fiscal_position_update in #381

**Comment by amcor** [comment]
account_invoice_line_description in https://github.com/OCA/account-invoicing/pull/387

**Comment by amcor** [comment]
account_invoice_line_sequence in https://github.com/OCA/account-invoicing/pull/388

**Comment by amcor** [comment]
account_invoice_pricelist in https://github.com/OCA/account-invoicing/pull/390

**Comment by emagdalenaC2i** [comment]
Are #347 account_invoice_supplier_ref_unique, account_invoice_customer_ref_unique or both?

**Comment by pedrobaeza** [comment]
It seems to be the first one.

**Comment by AMhadhbi** [comment]
I will work on account_invoice_view_payment

**Comment by pedrobaeza** [comment]
@AMhadhbi, noted.

**Comment by sudhir-erpharbor** [comment]
Any update on "stock_picking_invoicing" module?
Is WIP for this module or it won't be ported to v11?

**Comment by pedrobaeza** [comment]
@sudhir-erpharbor IMO migrating that module is a concept error, as the invoicing from sales/purchase orders is the best approach.

**Comment by sudhir-erpharbor** [comment]
@pedrobaeza  Thanks for your reply. What in the case if someone directly want to generate invoices from picking and don't want to create PO/SO?
I think in that case we should have option to create invoice from the picking (Delivery Order / Shipment)

Correct me if this feature is already available.
Thanks in advance.

**Comment by pedrobaeza** [comment]
No, it isn't available because for now, everyone has adapted to the correct flow: pre-create the order.

**Comment by sudhir-erpharbor** [comment]
I see. In this case I will migrate the module to v11 and maintain it in my branch in case anyone need it. Will that be fine if I do that?
@pedrobaeza

**Comment by pedrobaeza** [comment]
No problem, and you can even put it here in OCA, but what I'm saying is that you re-evaluate your flows as most of us have done and get to the same result: there's no need of this module, as maintaining such gigantic code and side effects doesn't worth.

**Comment by sudhir-erpharbor** [comment]
Thanks @pedrobaeza for your support. I had few inquiry about such flow so I thought it would be helpful to the people who are looking for this module.

**Comment by emagdalenaC2i** [comment]
Please add to the list account_invoice_refund_option, there is already a PR open #431 to migrate this module from 9 -> 11
account_invoice_blocking - By @astirpe - #331 is merged
account_invoice_merge - By @adrian-pesol - #365 is closed and superseded by #422 
there is a PR for account_invoice_line_sort in #413

**Comment by emagdalenaC2i** [comment]
@pedrobaeza account_invoice_refund_option isn't merged yet and it is mark in the list

**Comment by vipvalen** [comment]
El módulo account_group_invoice_line, se va migrar?, la contabilidad española con los asientos por producto es una barbaridad.

**Comment by pedroortega-punt** [comment]
Sorry for the language, The module account_group_invoice_line, will be migrated ?, Spanish accounting with the entries per product is outrageous.

**Comment by pedrobaeza** [comment]
I recommend you to not do that, or you will have several critical problems. Don't worry about the number of journal items. They are cheap.

**Comment by dsolanki-initos** [comment]
Hello all,
I have migarted the module account_group_invoice_line to v11 and here is the PR #824.

**Comment by fshah-initos** [comment]
Hello all,
I have migarted the module account_invoice_partner to v11 and here is the PR https://github.com/OCA/account-invoicing/pull/825

**Comment by dsolanki-initos** [comment]
Hello all,
I have migrated the module account_invoice_supplierinfo_update to v11 and here is the PR #829
